[package]
authors = ["Kilian Kilger <kkilger@gmail.com>"]
name = "rustirinth"
version = "0.1.0"

[dependencies]
failure = "~0.1"
failure_derive = "~0.1"
gdk ="~0.7"
cairo-rs = "~0.3"
lazy_static = "~1.0"
gtk = { version = "~0.3", features = ["v3_22"] } 
ndarray = "~0.11"
clap = "~2.30"


